### ISSUE TITLE
netgen on conda

### ISSUE THREAD

**Issue by trelau** [trelau/netgen#1]
@tpaviot I think I've managed to get win32 and win64 versions of netgen uploaded to anaconda:

https://anaconda.org/trelau/netgen

I installed on local machine and tried to build smesh but got a bunch of inconsistent dll linkage errors. I'll keep working it.

**Comment by tpaviot** [comment]
@trelau ok, perfect, I'll give it a try

**Comment by trelau** [comment]
@tpaviot Made a few commits to try and compile smesh + netgen.

https://github.com/trelau/smesh/commits/tp/netgen-support

I disabled the inconsistent dll linkage but so far haven't been able to get past this error:

https://ci.appveyor.com/project/trelau/smesh/build/smesh-6.7.1.7/job/7t3rnr89em846sro#L436

**Comment by tpaviot** [comment]
@trelau try removing /MD in CMakeLists.txt

**Comment by trelau** [comment]
@tpaviot I did that and added a definition for afxdll as shown here:

https://github.com/trelau/smesh/commit/2baf18adc68c3fe8c9bd12e89953c1a377089542

They both had the same result. See snapshot below:

![image](https://cloud.githubusercontent.com/assets/8950602/23051175/f0d7206e-f494-11e6-90f5-e2b3ae88ff6c.png)

Apparently windows.h should not be included but that is getting found when netgen includes meshing.hpp.

**Comment by tpaviot** [comment]
@trelau I'm building my own netgen, see https://github.com/tpaviot/netgen-conda

**Comment by trelau** [comment]
@tpaviot nice...wish i would have thought of that setting up the repo like that...

a few changes i made that might be relevant are:
-install nglib.h to include directory: https://github.com/trelau/netgen/commit/3eb637c94713ff77c65f3e17a3ea5428779765c8

-modified netgenconfig.cmake for smesh project: https://github.com/trelau/netgen/commit/9e30de97caedfff36e3dc377f6ba2db6dd7c8a5c

-install cmake files to Library/cmake: https://github.com/trelau/netgen/commit/3ab23c80c1168285570fda47bfcbd827178da638
